Updates rpm and deb distribution to adapt to admin password change (#4332)
Signed-off-by: Darshit Chanpura <dchanp@amazon.com>

diff --git a/scripts/pkg/build_templates/opensearch/deb/debian/preinst b/scripts/pkg/build_templates/opensearch/deb/debian/preinst
--- a/scripts/pkg/build_templates/opensearch/deb/debian/preinst
+++ b/scripts/pkg/build_templates/opensearch/deb/debian/preinst
@@ -11,6 +11,8 @@
 
 set -e
 
+OPENSEARCH_VERSION=CHANGE_VERSION
+
 echo "Running OpenSearch Pre-Installation Script"
 
 # Stop existing service
@@ -22,6 +24,29 @@ if command -v systemctl >/dev/null && systemctl is-active opensearch-performance
     echo "Stop existing opensearch-performance-analyzer.service"
     systemctl --no-reload stop opensearch-performance-analyzer.service
 fi
+
+# Check if OPENSEARCH_INITIAL_ADMIN_PASSWORD is defined
+# TODO:
+# 1. This check will need to be modified if there will be a min dist for deb in future (currently there is none)
+# 2. Currently, the demo config setup is defined to run, in postinst, if `opensearch-security` is present. Cannot apply the same check here since the plugins folder is not available yet.
+
+# Check if this is an upgrade by checking whether opensearch already exists
+if dpkg-query -W opensearch >/dev/null 2>&1; then
+    OPENSEARCH_ALREADY_INSTALLED=yes
+else
+    OPENSEARCH_ALREADY_INSTALLED=no
+fi
+
+OPENSEARCH_REQUIRED_VERSION="2.12.0"
+MINIMUM_OF_TWO_VERSIONS=`echo $OPENSEARCH_REQUIRED_VERSION $OPENSEARCH_VERSION | tr ' ' '\n' | sort -V | uniq | head -n 1`
+
+if [ $OPENSEARCH_ALREADY_INSTALLED = no ]; then
+  if [ $MINIMUM_OF_TWO_VERSIONS = $OPENSEARCH_REQUIRED_VERSION ] && [ -z "$OPENSEARCH_INITIAL_ADMIN_PASSWORD" ]; then
+    echo "ERROR: Opensearch 2.12 and later requires the env variable OPENSEARCH_INITIAL_ADMIN_PASSWORD to be defined to setup the opensearch-security demo configuration"
+    exit 1
+  fi
+fi
+
 
 # Create user and group if they do not already exist.
 getent group opensearch > /dev/null 2>&1 || groupadd -r opensearch
