Handles upgrade scenarios for preinst and addresses PR comments
Signed-off-by: Darshit Chanpura <dchanp@amazon.com>

diff --git a/scripts/pkg/build_templates/opensearch/deb/debian/preinst b/scripts/pkg/build_templates/opensearch/deb/debian/preinst
--- a/scripts/pkg/build_templates/opensearch/deb/debian/preinst
+++ b/scripts/pkg/build_templates/opensearch/deb/debian/preinst
@@ -26,14 +26,21 @@ if command -v systemctl >/dev/null && systemctl is-active opensearch-performance
 fi
 
 # Check if OPENSEARCH_INITIAL_ADMIN_PASSWORD is defined
-# NOTE:
+# TODO:
 # 1. This check will need to be modified if there will be a min dist for deb in future (currently there is none)
 # 2. Currently, the demo config setup is defined to run, in postinst, if `opensearch-security` is present. Cannot apply the same check here since the plugins folder is not available yet.
+
+# Check if this is an upgrade by checking whether opensearch already exists
+OPENSEARCH_INSTALLED=$(dpkg -l | grep opensearch)
+
 OPENSEARCH_REQUIRED_VERSION="2.12.0"
 COMPARE_VERSION=`echo $OPENSEARCH_REQUIRED_VERSION $OPENSEARCH_VERSION | tr ' ' '\n' | sort -V | uniq | head -n 1`
-if [ "$COMPARE_VERSION" == "$OPENSEARCH_REQUIRED_VERSION" ] && [ -z "$OPENSEARCH_INITIAL_ADMIN_PASSWORD" ]; then
-  echo "ERROR: Opensearch 2.12 and later requires the env variable OPENSEARCH_INITIAL_ADMIN_PASSWORD to be defined to setup the opensearch-security demo configuration"
-  exit 1
+
+if [ -n "$OPENSEARCH_INSTALLED" ] && [ $OPENSEARCH_VERSION != CHANGE_VERSION ]; then
+  if [ "$COMPARE_VERSION" == "$OPENSEARCH_REQUIRED_VERSION" ] && [ -z "$OPENSEARCH_INITIAL_ADMIN_PASSWORD" ]; then
+    echo "ERROR: Opensearch 2.12 and later requires the env variable OPENSEARCH_INITIAL_ADMIN_PASSWORD to be defined to setup the opensearch-security demo configuration"
+    exit 1
+  fi
 fi
 
 
