Enable integration test failure notification via GitHub issues (#3395)
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

diff --git a/jenkins/opensearch/integ-test.jenkinsfile b/jenkins/opensearch/integ-test.jenkinsfile
--- a/jenkins/opensearch/integ-test.jenkinsfile
+++ b/jenkins/opensearch/integ-test.jenkinsfile
@@ -1,4 +1,4 @@
-lib = library(identifier: 'jenkins@2.1.0', retriever: modernSCM([
+lib = library(identifier: 'jenkins@4.0.0', retriever: modernSCM([
     $class: 'GitSCMSource',
     remote: 'https://github.com/opensearch-project/opensearch-build-libraries.git',
 ]))
@@ -85,6 +85,7 @@ pipeline {
                     env.buildId = buildManifestObj.getArtifactBuildId()
                     env.distribution = buildManifestObj.getDistribution()
                     env.version = buildManifestObj.build.version
+                    env.platform = buildManifestObj.build.platform
                     env.artifactPath = buildManifestObj.getArtifactRoot(BUILD_JOB_NAME, buildId)
                     env.AGENT_LABEL = agent_nodes["$architecture"]
 
@@ -118,8 +119,8 @@ pipeline {
                     echo "componentList: ${componentList}"
 
                     for (component_check in componentList) {
-                        if (! componentDefaultList.contains(component_check)) {
-                           error("${component_check} is not in build manifest: ${componentDefaultList}, exit 1") 
+                        if (!componentDefaultList.contains(component_check)) {
+                            error("${component_check} is not in build manifest: ${componentDefaultList}, exit 1")
                         }
                     }
 
@@ -159,12 +160,12 @@ pipeline {
                                                 stage("Run Integtest ${local_component}") {
                                                     echo "Component Name: ${local_component}"
                                                     // Jenkins tend to not clean up workspace at times even though ws clean is called
-                                                    // Due to docker is mounting the agent directory so it can communicated with the agent
-                                                    // This sometimes causes the workspace to retain last run test-results and ends with build failures
+                                                    // Docker is mounting the agent directory so it can communicate with the agent
+                                                    // this sometimes causes the workspace to retain last run test-results and ends with build failures
                                                     // https://github.com/opensearch-project/opensearch-build/blob/6ed1ce3c583233eae4fe1027969d778cfc7660f7/src/test_workflow/test_recorder/test_recorder.py#L99
                                                     sh("echo ${local_component} with index ${local_component_index} will sleep ${wait_seconds} seconds to reduce load && sleep ${wait_seconds}")
                                                     unstash "integtest-opensearch-$BUILD_NUMBER"
-                                                    sh("rm -rf test-results")
+                                                    sh('rm -rf test-results')
                                                     runIntegTestScript(
                                                         jobName: "$BUILD_JOB_NAME",
                                                         componentName: "${local_component}",
@@ -175,8 +176,15 @@ pipeline {
                                                     )
                                                 }
                                             } catch (e) {
-                                                echo "Error running integtest for component ${local_component}"
-                                                throw e
+                                                echo "Error running integtest for component ${local_component}, creating Github issue"
+                                                String issueBodyMessage =  "The integration test failed at distribution level for component ${local_component} for version: ${version}<br><br>Please check the logs: ${RUN_DISPLAY_URL}<br><br> * Steps to reproduce: See https://github.com/opensearch-project/opensearch-build/tree/main/src/test_workflow#integration-tests<br>* Access cluster logs:<br> - [With security](https://ci.opensearch.org/ci/dbc/${JOB_NAME}/${version}/${buildId}/${platform}/${architecture}/${distribution}/test-results/${BUILD_NUMBER}/integ-test/${local_component}/with-security/local-cluster-logs/stdout.txt) (if applicable)<br> - [Without security](https://ci.opensearch.org/ci/dbc/${JOB_NAME}/${version}/${buildId}/${platform}/${architecture}/${distribution}/test-results/${BUILD_NUMBER}/integ-test/${local_component}/without-security/local-cluster-logs/stdout.txt) (if applicable)<br><br> _Note: All in one test report manifest with all the details coming soon. See https://github.com/opensearch-project/opensearch-build/issues/1274_"
+                                                createGithubIssue(
+                                                    repoUrl: buildManifestObj.getRepo("${local_component}"),
+                                                    issueTitle: "Integration Test failed for component ${local_component}: ${version}",
+                                                    issueBody: issueBodyMessage,
+                                                    label: "autocut,v${version},integ-test-failure"
+                                                )
+                                                throw new Exception("Error running integtest for component ${local_component}", e)
                                             } finally {
                                                 echo "Completed running integtest for component ${local_component}"
                                                 uploadTestResults(
