Add curl validation for standalone sign artifact workflows (#2514)
* Add curl validation for standalone sign artifact workflows

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

* Add curl validation for standalone sign artifact workflows

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

* Add curl validation for standalone sign artifact workflows

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

* Add curl validation for standalone sign artifact workflows

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

* Update tests

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

* Allow empty trigger

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

diff --git a/jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile b/jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
--- a/jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
+++ b/jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
@@ -110,7 +110,21 @@ List downloadArtifactsFromUrls() {
         trimmedUrl = url.trim()
         filename = trimmedUrl.substring(trimmedUrl.lastIndexOf('/') + 1)
         downloadedFiles.add(filename)
-        sh "curl -SL ${trimmedUrl} -o ${WORKSPACE}/artifacts/${filename}"
+        sh """
+            set +x
+            set -e
+
+            STATUS_CODES=`curl -IL ${trimmedUrl} 2>&1 | grep -Eo "HTTP/[12] [0-9]+" | grep -Eo '[0-9][0-9][0-9]' | sort | uniq`
+            for resp_code in \$STATUS_CODES; do
+                if echo \$resp_code | grep -qEo '[45][0-9][0-9]'; then
+                    echo "Error url with error response code \$resp_code, exit 1"
+                    exit 1
+                fi
+            done
+
+            echo "No error detected, valid response \$resp_code, downloading ${trimmedUrl}"
+            curl -SL ${trimmedUrl} -o ${WORKSPACE}/artifacts/${filename}
+        """
     }
 
     return downloadedFiles
