deb - Listen to DISABLE_INSTALL_DEMO_CONFIG

diff --git a/scripts/pkg/build_templates/current/opensearch/deb/debian/postinst b/scripts/pkg/build_templates/current/opensearch/deb/debian/postinst
--- a/scripts/pkg/build_templates/current/opensearch/deb/debian/postinst
+++ b/scripts/pkg/build_templates/current/opensearch/deb/debian/postinst
@@ -21,7 +21,9 @@ pid_dir=/var/run/opensearch
 
 # Apply Security Settings
 if [ -d ${product_dir}/plugins/opensearch-security ]; then
-    bash ${product_dir}/plugins/opensearch-security/tools/install_demo_configuration.sh -y -i -s > ${log_dir}/install_demo_configuration.log 2>&1 || (echo "ERROR: Something went wrong during demo configuration installation. Please see the logs in ${log_dir}/install_demo_configuration.log" && exit 1)
+    if [ ! "$DISABLE_INSTALL_DEMO_CONFIG" = "true" ]; then
+        bash ${product_dir}/plugins/opensearch-security/tools/install_demo_configuration.sh -y -i -s > ${log_dir}/install_demo_configuration.log 2>&1 || (echo "ERROR: Something went wrong during demo configuration installation. Please see the logs in ${log_dir}/install_demo_configuration.log" && exit 1)
+    fi
 fi
 # Apply PerformanceAnalyzer Settings
 chmod a+rw /tmp
